### ISSUE TITLE
searching a card by name of the card give me error 500.

### ISSUE THREAD

**Issue by recor-boop** [seastan/ringsdb#133]
the problem occured a few days ago :/
my user account is Recor

**Comment by OleksandrBerchenko** [comment]
@recor-boop Does the issue still exist?

**Comment by recor-boop** [comment]
Not now, thank you 👌🏽
All is functional now 🙏🏽

Téléchargez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : Oleksandr Berchenko ***@***.***>
Envoyé : Thursday, August 4, 2022 2:50:50 PM
À : seastan/ringsdb ***@***.***>
Cc : recor-boop ***@***.***>; Mention ***@***.***>
Objet : Re: [seastan/ringsdb] searching a card by name of the card give me error 500. (Issue #133)


@recor-boop<https://github.com/recor-boop> Does the issue still exist?
