### ISSUE TITLE
Decklists endpoint returns a `500` error response

### ISSUE THREAD

**Issue by sashebalchev** [seastan/ringsdb#142]
Nothing more to add as info.
The `Decklists` endpoint/page returns `500` and shows this message `The server encountered an error 500. Please report it on GitHub.`

I'm pretty sure it worked well two days ago once I got back to the game and remembered the website. Great work supporting the new products coming from FFG. Very glad to see it still standing as it will be an invaluable resource for helping me build some decks and track my collection. :)

**Comment by seastan** [comment]
Fixed. The server had run out of disk space. Thanks!
