### ISSUE TITLE
Support for new players at the cardgame that are buying only the Repackaged Expansions

### ISSUE THREAD

**Issue by adrumetris** [seastan/ringsdb#147]
Hello! I'm new at the game, and here in Brasil we don't have all the expansions packages that were lauched over the years. But now, we are getting all the Repackaged Expansions!

I love the ringsdb, since I started playing, the site helped a lot with deckbuilding and knowledging of the game itself. But there is an issue selection the adventure packs in My Collection section.

I can select the content of the first print of the game, the new heros expansions (from Dwarves of Durin, Elves of Lórien, Defenders of Gondor and Riders of Rohan), and the campaing new cards isolated. 

But, I bought the Angmar Awakened hero and saga expansions, and the site doesn't understand all the hero cards I have to build decks, like the red Aragorn (that's in the Angmar Awakened hero expansion) . So it's a bit hard to search for decklists with only cards i own, because i own more cards than the site understands.

As a suggestion, it could separate the heros expansions that FFG has re-lanched (and will re-lauch), like where the decks of hero mentioned before is right know.(Dwarves of Durin, Elves of Lórien, Defenders of Gondor and Riders of Rohan).

I atached some prints to serve as an exemple!
![My Collection](https://user-images.githubusercontent.com/46167890/216428080-3a6659d5-c341-4eeb-b578-ff517d756069.png)

![Angmar Awakened](https://user-images.githubusercontent.com/46167890/216428059-4be1eb14-434f-46cd-86fc-7e9147c9d57a.jpeg)

![Aragorn Search in Decklist 1](https://user-images.githubusercontent.com/46167890/216428070-b3a06c88-54f3-452e-851a-ff8fee19a7d8.png)

![Aragorn Search in Decklist 2](https://user-images.githubusercontent.com/46167890/216428075-194e5037-36cb-42b0-a1ae-bd3af733d485.png)

![Dunedain](https://user-images.githubusercontent.com/46167890/216428687-d1cc0473-2b70-4714-8b66-84d6221b4720.png)

**Comment by baptistemanson** [comment]
Repackaged expansion also contains the Lost Realms. Check this and you are good to go.
