### ISSUE TITLE
Quest Logs is down

### ISSUE THREAD

**Issue by iainreid** [seastan/ringsdb#2]
Some kind of server error.  Tested with my account (which has had username changes) and with a fresh new account (with none).

"The server encountered an error 500. Please report it on GitHub."

**Comment by seastan** [comment]
Thanks for reporting. Are you using Safari by any chance?

**Comment by iainreid** [comment]
Chrome.  Just tested on Edge also - same result.

**Comment by clatshaw** [comment]
Does the server error occur whenever you are trying to navigate to your quest logs? (via My Collections > Quest Logs)

**Comment by clatshaw** [comment]
It looks like the main Quest Logs page is running as expected, but I am able to replicate the server error whenever I'm signed in as a user with no quest logs, and go to My Collections > Quest Logs page.

I'm guessing that there is a initialization error when the page is trying to pull the quest logs from a fresh account and there's not a null reference check when creating the page.

**Comment by iainreid** [comment]
Yes, it only occurs on My Collections -> Quest Logs.  The global Quest Logs page is fine.  Apologies, I should have been clear.

**Comment by seastan** [comment]
@clatshaw Thanks for tracking down the source of this error. I think you are correct in that it is related to having no quest logs. I will take a look at this today.

**Comment by seastan** [comment]
@iainreid In the meantime you should be able to log a quest by going to a deck and clicking the "Log a quest button". Once you've logged one, the "My Collections -> Quest Logs" should start working.

**Comment by seastan** [comment]
Fixed by #3
