### ISSUE TITLE
Updating card images/text?

### ISSUE THREAD

**Issue by xdg** [seastan/ringsdb#25]
Hi.  I've noticed some cards on Hall of Beorn have post-errata text but the same cards on RingsDB have pre-errata text (both in text and on images).  Is there a way I can help update the images/text on RingsDB to match Hall of Beorn?

**Comment by xdg** [comment]
Are the rescans from reprints?  I assumed someone just photoshopped them.

**Comment by xdg** [comment]
I've gone through all the player cards that Hall of Beorn has listed as having errata and update my lists above.  Found a few more that can be updated and a lot more that need some image photoshopping.

**Comment by seastan** [comment]
Yeah, generally if you see a picture of a card with updated text, it's because someone has scanned it.

**Comment by seastan** [comment]
I've updated the other old text you identified. Thanks!

**Comment by danpoage** [comment]
Hall of Beorn has updated images for all of these except:
- Wandering Took (Core)
- Out of the Wild (Road to Rivendell)
- Blue Mountain Trader (The Dunland Trap)
I was unable to find new scans for the above cards, but once I do I will update them the the errata versions as well. Please note that you will likely need to clear your browser cache before you see the new images.

**Comment by xdg** [comment]
@seastan I photoshopped those three and Dan has added them to Hall of Beorn, so I've changed the title of the long list above as are reminder that they all need image updates.

**Comment by seastan** [comment]
All text and images have no been updated. That's so much for all your work in compiling the list @xdg !
