### ISSUE TITLE
Missing images

### ISSUE THREAD

**Issue by xdg** [seastan/ringsdb#39]
The card database from the API shows several cards are missing images.  Looks like mostly contracts and recently released cards -- though Hall of Beorn does seem to be up to date through Fortress of Nurn:

```
Gandalf (Two-Player Limited Edition Starter)
The Burglar's Turn (Wrath and Ruin)
Forth, The Three Hunters! (The City of Ulfast)
The Grey Wanderer (Challenge of the Wainriders)
Gildor Inglorion (Under the Ash Mountains)
Wandering Exile (Under the Ash Mountains)
Valiant Sword (Under the Ash Mountains)
Stone of Elostirion (Under the Ash Mountains)
Well Preserved (Under the Ash Mountains)
Northern Bowmaster (Under the Ash Mountains)
Reckless Attack (Under the Ash Mountains)
Odo Proudfoot (Under the Ash Mountains)
Defiant Challenge (Under the Ash Mountains)
Helm of Secrecy (Under the Ash Mountains)
Council of the Wise (Under the Ash Mountains)
Messenger of the King (The Land of Sorrow)
Bond of Friendship (The Fortress of Nurn)
(MotK) Odo Proudfoot (Messenger of the King Allies)
```

**Comment by OleksandrBerchenko** [comment]
An updated list:
The Burglar's Turn (Wrath and Ruin)
Forth, The Three Hunters! (The City of Ulfast)
The Grey Wanderer (Challenge of the Wainriders)
Council of the Wise (Under the Ash Mountains)
Messenger of the King (The Land of Sorrow)
all cards from The Fortress of Nurn
Gandalf #2 (Two-Player Limited Edition Starter)
A Perilous Voyage (The Hunt for the Dreadnaught)
all Boon (Treasure) cards from The Lord of the Rings

Additionally, some cards still have outdated images with a watermark.  For example: https://ringsdb.com/card/18003 or https://ringsdb.com/card/146004.

**Comment by OleksandrBerchenko** [comment]
Everything is already updated.
