### ISSUE TITLE
Error 500 when opening a deck

### ISSUE THREAD

**Issue by egbert86** [seastan/ringsdb#4]
Hi,

This morning I tried to look at this deck:

https://ringsdb.com/decklist/view/7991/road-to-rivendell-1.0

I got a message that "The server encountered an error 500" and that it should be reporterd. 

Thanks in advance!

**Comment by clatshaw** [comment]
I wonder if it has something to do with the name of the deck being the same as a scenario. 

I get the same error when I look at these decks:
https://ringsdb.com/decklist/view/6491/the-passage-through-mirkwood-2.0
https://ringsdb.com/decklist/view/8263/the-long-dark-1.0

However, this doesn’t explain why some of three of these decks load properly and the 4th throws the error:
https://ringsdb.com/decklist/view/850/flight-to-the-ford-1.0
https://ringsdb.com/decklist/view/7517/flight-to-the-ford-1.0
https://ringsdb.com/decklist/view/4298/flight-to-the-ford-1.0
https://ringsdb.com/decklist/view/5646/flight-to-the-ford-1.0

Furthermore, it’s peculiar why all three of this author’s decks also have the same server error:
https://ringsdb.com/decklists/find?author=Jagrelius

It looks like all of those decks are trying to render the navigation pane again, but stops at the Quest Logs tab which would make sense that that is what is causing the page to freak out. But then the question becomes why is it trying to show the tabs again in the first place...

**Comment by seastan** [comment]
@clatshaw Well the first scenario is just called "Passage through Mirkwood" (no "The"), so I don't think that's it.

Also, the 4th Flight deck you linked does load for me.

None of Jagrelius' decks load though. Strange.

**Comment by clatshaw** [comment]
@seastan Sorry, I didn’t realize my the observation of the Flight decks was ambiguous. I just meant that one of the four decks doesn’t load (the second deck doesn’t load for me). 

It’s odd that the linked decks that don’t work were created at least a year ago. If they were more recent, it would make sense that the quest log feature would cause the issue.

I’m not home right now, but I can take a look at those pages to see if I can find anything.

**Comment by Galdor83** [comment]
Same error on:

[https://ringsdb.com/decklist/view/11601/coresetshadowsofmirkwoodi-ii-iii-3.0](https://ringsdb.com/decklist/view/11601/coresetshadowsofmirkwoodi-ii-iii-3.0)
[https://ringsdb.com/decklist/view/11658/shadowsofmirkwoodiv-v-4.0](https://ringsdb.com/decklist/view/11658/shadowsofmirkwoodiv-v-4.0)
[https://ringsdb.com/decklist/view/11676/shadowsofmirkwoodvi-1.0](https://ringsdb.com/decklist/view/11676/shadowsofmirkwoodvi-1.0)

**Comment by wlk0** [comment]
Also got a 500 on [http://ringsdb.com/decklist/view/9408/chad-s-campaign-the-tower-of-cirith-ungol-1.0](http://ringsdb.com/decklist/view/9408/chad-s-campaign-the-tower-of-cirith-ungol-1.0)

**Comment by jtwilliams37** [comment]
Getting the same error here if it's helpful at all for debugging:

https://ringsdb.com/decklist/view/11614/thechoiceoflthien-1.0
https://ringsdb.com/decklist/view/10674/thranduil-the-elvenking-1.0

Thanks Seastan!

**Comment by seastan** [comment]
Fixed by #16
