### ISSUE TITLE
Select allowed sets doesn't permit core set quantity

### ISSUE THREAD

**Issue by vgambit** [seastan/ringsdb#8]
I only dipped so much of my foot into LotR LCG, so I only have one core set. However, basically all the decklists I'm seeing assume I have 3, so they're not quite useful. Any chance of enabling additional options for specifying that I have 1, 2, or 3 core sets, and leaving out the decklists that asks for more copies of certain cards than I have?

**Comment by seastan** [comment]
I'll add this to the list of feature requests. In the meantime, have you considered using proxies of the 1x and 2x core set cards? It can really open up your deckbuilding options without needing to purchase multiple core sets.

**Comment by vgambit** [comment]
Thanks!

I appreciate the workaround suggestion, but I'd probably move on from this game before I go down that road. To be honest, this is the only game I own that even warrants a site like RingsDB. Every other game, for the most part, kinda just works fine on its own outta the box. Not saying LotR doesn't, but the deckbuilding aspect makes it difficult to evaluate, as I can't tell how much of my frustration comes from my back deck construction abilities vs simply not meshing with the game itself.

**Comment by seastan** [comment]
What is your card pool? Is it just the core set or do you have other packs? Maybe I can recommend something that is single-core friendly.

**Comment by vgambit** [comment]
I have the core set and 6 packs, a mix of adventure and deluxe content. I appreciate the offer, but the use case I had in mind was picking a scenario, finding a fellowship for it, then playing that scenario with it. As it stands, to do that, I'd have to go through each fellowship, start putting decks together, and stop when I realize it asks for more cards than I have, moving on to the next one. I did that twice before I gave up.

**Comment by seastan** [comment]
In that case, make sure you have only 1 core set selected in My Collection->Adventure Packs. Then, when viewing a fellowship, any cards that you don't have enough of will have orange numbers so you can immediately tell.

![chrome_DAsR5kO5bW](https://user-images.githubusercontent.com/9059540/58300344-f9bd2600-7d96-11e9-961d-299cd2b1cf8c.png)

**Comment by vgambit** [comment]
Never noticed that. And of course, it's clearly explained when you hover over the number. I think it should be made impossible to miss or misinterpret, since I definitely got a +1-type comment when I brought this up on /r/lotrlcg. Maybe a red background on each card that you don't have enough of. But I would honestly expect fellowships that need more cards than I have to simply not appear in the results if I have that filtering set up, as that's supposed to be the point, or at least intention of that filter AFAIK.

**Comment by seastan** [comment]
Limiting fellowship searching (vs single decklist) by your collection gets a little tricky because it's legal to have say, 9 Daerons Runes in a 3-player fellowship. But there's no way to indicate in your collection that you have 3 copies of the Foundations of Stone adventure pack. So while I could add a text field next to every pack to indicate how many of that pack you have, it would be a fair amount of work, and no one has really requested such a feature before.

That's why the "select allowed packs" doesn't discriminate against the number of card copies. But adding in a feature just for core sets is something I can look into.

**Comment by seastan** [comment]
I have added couple new options to the fellowship search to make your use case more user friendly. Hope it helps!

https://ringsdb.com/fellowships/search
